base_code/personal_site/personal_site/urls.py
from django.conf.urls import url
from django.contrib import admin 
from personalApplication import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls), 
    url(r'^emp', views.emp),  
    url(r'^show',views.show),
    url(r'^upload/', views.upload),
    url(r'^edit/(?P<id>[\w-]+)', views.edit),  
    url(r'^update/(?P<id>[\w-]+)', views.update),  
    url(r'^delete/(?P<id>[\w-]+)', views.destroy),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
]
 

base_code/personal_site/personalApplication/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
 
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    class Meta:  
        db_table = "employee"  

base_code/personal_site/personalApplication/forms.py
from django import forms  
from personalApplication.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  


class StudentForm(forms.Form):  
    firstname = forms.CharField(label="Image Name",max_length=50)  
    lastname  = forms.CharField(label="Album Name", max_length = 50)  
    file      = forms.FileField() # for creating file input  

base_code/personal_site/personalApplication/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django.shortcuts import render, redirect  
from personalApplication.forms import EmployeeForm  
from personalApplication.models import Employee
from django.contrib.auth.decorators import login_required
from personalApplication.functions import handle_uploaded_file  
from personalApplication.forms import StudentForm
from django.http import HttpResponse 
# Create your views here.  

@login_required
def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = EmployeeForm() 
    return render(request,'index.html',{'form':form})

@login_required(login_url='/login/')  
def show(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})

@login_required  
def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})

@login_required  
def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})
    
@login_required  
def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")

@login_required
def upload(request):  
    if request.method == 'POST':  
        student = StudentForm(request.POST, request.FILES)  
        if student.is_valid():  
            handle_uploaded_file(request.FILES['file'])  
            return HttpResponse("File uploaded successfuly")  
    else:  
        student = StudentForm()  
        return render(request,"upload.html",{'form':student})

base_code/personal_site/personalApplication/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous">
    {% load staticfiles %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
    .mySlides {display:none;}
    </style> 
  <title>{% block title %}Login{% endblock %}</title>
</head>
<body>
  <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="http://127.0.0.1:8000/">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="http://127.0.0.1:8000/show">Show Employee<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="http://127.0.0.1:8000/upload/">Upload Photo<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="">Gallery<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              State
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="#">Action</a>
                              <a class="dropdown-item" href="#">Another action</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                          </li>
                  </ul>
                  {% if user.is_authenticated %}
                Hi {{ user.username }}!
                <a href="{% url 'logout' %}" class="btn btn-primary">logout</a>
                {% else %}
                <a href="{% url 'login' %}" class="btn btn-primary">login</a>
                {% endif %}
                
                  <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
              </nav>
    <!-- <h1><center>LOGIN PAGE</center></h1> -->
  </header>
  <hr>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <hr>
  <footer>
    <h6><center>copyright © 2019 Gopinath</center></h6>
  </footer>
</body>
</html>

base_code/personal_site/personalApplication/templates/edit.html
{% extends 'base.html' %}

{% block title %}Edit{% endblock %}

{% block content %}
<div class="container">
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
    {% csrf_token %}    
<br>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<h3>Update Details</h3>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Id:</label>  
<div class="col-sm-4">  
    <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Name:</label>  
<div class="col-sm-4">  
    <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Email:</label>  
<div class="col-sm-4">  
    <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Contact:</label>  
<div class="col-sm-4">  
    <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-success">Update</button>  
</div>  
</div>  
</form> 
</div> 
  
{% endblock %}

base_code/personal_site/personalApplication/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% load staticfiles %} 
<h2><center>WELCOME</center></h2>
<div class="w3-content w3-display-container">
    <img class="mySlides" src="{% static 'img/a.jpg' %}" style="width:100%">
    <img class="mySlides" src="{% static 'img/b.jpg' %}" style="width:100%">
    <img class="mySlides" src="{% static 'img/c.jpeg' %}" style="width:100%">
    
    <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
    <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
</div>
<script>
     var slideIndex = 1;
     showDivs(slideIndex);
    
     function plusDivs(n) {
       showDivs(slideIndex += n);
     }

     function showDivs(n) {
       var i;
       var x = document.getElementsByClassName("mySlides");
       if (n > x.length) {slideIndex = 1}
       if (n < 1) {slideIndex = x.length}
       for (i = 0; i < x.length; i++) {
         x[i].style.display = "none";  
       }
       x[slideIndex-1].style.display = "block";  
     }
</script>
  
{% endblock %}

base_code/personal_site/personalApplication/templates/index.html
{% extends 'base.html' %}

{% block title %}Insert{% endblock %}

{% block content %}
<form method="POST" class="post-form" action="/emp">  
    {% csrf_token %}  
<div class="container">  
<br>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<h3>Enter Details</h3>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Id:</label>  
<div class="col-sm-4">  
  {{ form.eid }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Name:</label>  
<div class="col-sm-4">  
  {{ form.ename }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Email:</label>  
<div class="col-sm-4">  
  {{ form.eemail }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Contact:</label>  
<div class="col-sm-4">  
  {{ form.econtact }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-primary">Submit</button>  
</div>  
</div>  
</div>  
</form> 
  
{% endblock %}

base_code/personal_site/personalApplication/templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a>again.</p>
{% endblock %}

base_code/personal_site/personalApplication/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

base_code/personal_site/personalApplication/templates/show.html
{% extends 'base.html' %}

{% block title %}Show{% endblock %}

{% block content %}
<table class="table table-striped table-bordered table-sm">  
        <thead class="thead-dark">  
        <tr>  
            <th>Employee ID</th>  
            <th>Employee Name</th>  
            <th>Employee Email</th>  
            <th>Employee Contact</th>  
            <th>Actions</th>  
        </tr>  
        </thead>  
        <tbody>  
    {% for employee in employees %}  
        <tr>  
            <td>{{ employee.eid }}</td>  
            <td>{{ employee.ename }}</td>  
            <td>{{ employee.eemail }}</td>  
            <td>{{ employee.econtact }}</td>  
            <td>  
                <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
                <a href="/delete/{{ employee.id }}">Delete</a>  
            </td>  
        </tr>  
    {% endfor %}  
        </tbody>  
    </table>  
    <br>  
    <br>  
    <center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
  
{% endblock %}

base_code/personal_site/personalApplication/templates/upload.html
 {% extends 'base.html' %}

 {% block title %}Upload{% endblock %}
 
 {% block content %}
 <div class="container">
 <h3><center>Upload Photos</center></h3>
 <div align="center">
        <form method="POST" class="post-form" enctype="multipart/form-data">  
                {% csrf_token %}  
                {{ form.as_p }}  
                <button type="submit" class="save btn btn-default">Save</button>  
        </form> 

 </div>
 </div>
    
{% endblock %} 